### PR TITLE
Feat/redesigning

### PR DESCRIPTION
**Pull request by zikosichi**
Complete redesign of the application. Enjoy :)

image

image

### CODE REVIEW

**Comment by prashantpalikhe** [comment]
Holy crap! Amazing. 

The only reason I am not using this awesome app as much as I should is that it was missing the sexiness. 

This looks amazing!

**Comment by inishchith** [comment]
What just happened 🐒 
@zikosichi Give me some time to review this 😛

**Comment by zikosichi** [comment]
Hahaa :)) Hope you will like it ;)

**Comment by zikosichi** [comment]
It was @prashantpalikhe `s initiative

**Comment by inishchith** [comment]
Thanks! @zikosichi @prashantpalikhe 
These look so good. 
I'll get back once i review it completely.

PS: We're so close to 100 🌟 🥊

**Comment by inishchith** [comment]
@zikosichi Thanks for contributing!. 
Really appreciate it.
I'll update `Readme` once i've fixed issues for smaller screens ( some of them shown below ). 

screenshot 2019-02-03 at 11 31 51 pm

**Comment by zikosichi** [comment]
Great, will fix those issues as well

**Pull request merged**
