### PR TITLE
Add share with friend feature

### PR DESCRIPTION
**Pull request by XLAR-8**
#16  Add share link button on the MapView

### CODE REVIEW

**Comment by inishchith** [comment]
@XLAR-8 Can you please keep the changes that are relevant to this PR and remove others?

Thanks!

**Comment by XLAR-8** [comment]
@inishchith please take a look.

**Comment by inishchith** [comment]
@XLAR-8 The changes looks good to me.
I would add an Icon instead of just the text("share"). What do you think?

**Comment by XLAR-8** [comment]
Great, I will do that.

**Review by inishchith — APPROVED** [review]
@XLAR-8 Thanks for your work! ✨

**Pull request merged**
